modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL-3.0 License"
issueTrackerURL = "https://github.com/Janoeo/Wool-Armor/issues"
[[mods]]
modId = "wool_armor"
version = "${file.jarVersion}"
displayName = "Wool Armor"
displayURL = "https://github.com/Janoeo/Wool-Armor"
authors = "AlasDiablo, Safyrus"
description = '''
This mod just add wool armor
'''
[[dependencies.wool_armor]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wool_armor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wool_armor]]
modId = "diolib"
mandatory = true
versionRange = "[3.3,)"
ordering = "NONE"
side = "BOTH"
