modLoader = "javafml"
loaderVersion = "[37,)"
license = "LGPL-3.0"
[[mods]]
modId = "wool_armor"
version = "${file.jarVersion}"
displayName = "Wool Armor"
authors = "AlasDiablo, lIotaMiu, Safyrus"
description = '''
Hello o/
'''
[[dependencies.wool_armor]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wool_armor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "BOTH"
[[dependencies.wool_armor]]
modId = "diolib"
mandatory = true
versionRange = "[2.0.17,)"
ordering = "NONE"
side = "BOTH"