modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPL-3.0 License"
issueTrackerURL = "https://github.com/Janoeo/Wool-Armor/issues"
[[mods]]
    modId = "wool_armor"
    version = "${file.jarVersion}"
    displayName = "Wool Armor"
    displayURL = "https://github.com/Janoeo/Wool-Armor"
    authors = "AlasDiablo, Safyrus"
    description = '''
    This mod just add wool armor
    '''
[[dependencies.wool_armor]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.wool_armor]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.wool_armor]]
    modId = "diolib"
    mandatory = true
    versionRange = "[6.7.32,)"
    ordering = "NONE"
    side = "BOTH"
